name: Karrie Huang
headline: Independent, curious, and smart, I hope.
standfirst: "Final year of philosophy, politics and economics at Lady Margaret
  Hall, Oxford. Grew up in Palo Alto. Now an AI product person: dreaming,
  designing and building."
description: Independent, curious, and smart, I hope. Final year of philosophy,
  politics and economics at Lady Margaret Hall, Oxford. Grew up in Palo Alto. An
  AI product person.
linkedin: https://www.linkedin.com/in/karrie-h-675123207/
